name: Update docker dev image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Create .env.development file
        env:
          PORT: ${{ secrets.PORT }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          NODE_ENV: development
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          ORIGIN: "*"
        run: |
          echo "PORT=${PORT}" >> .env.development
          echo "MONGODB_URI=${MONGODB_URI}" >> .env.development
          echo "NODE_ENV=${NODE_ENV}" >> .env.development
          echo "JWT_SECRET=${JWT_SECRET}" >> .env.development
          echo "ORIGIN=${ORIGIN}" >> .env.development
          
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/swifty-order-service .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/swifty-order-service
